[project]
name = "sentance_poc"
version = "0.1.0"

dependencies = [
    "pip",
    "pre-commit",
    "pytest",
    "pytest-cov",
    "h5py",
    "mwxml",
    "numpy",
    "matplotlib",
    "pandas",
    "scipy",
    "cython",
    "jupyter",
    "notebook",
    "colorcet",
    "tqdm",
    "mwparserfromhell",
    "sentence-transformers",
    "pytorch-lightning",
]
